Allow to maintain multiple override files
shiftstack/dev-install pull request #60
Opened 2021-05-12 19:13 UTC by EmilienM

Most of us maintain multiple overrides depending where they deploy.
Let's allow our users to maintain multiple files, e.g.:

- local-overrides-beaker.yaml
- local-overrides-vexxhost.yaml
- etc

And when deploying they do: `make osp_full
overrides=local-overrides-beaker.yaml`.

This is backward compatible and the default will remain
local-overrides.yaml.

2021-05-12 20:00 UTC, mdbooth requested changes
Nice! Looks like it needs a minor fix in the Makefile and then it's good to go.

2021-05-12 20:03 UTC, EmilienM commented on Makefile
>  local-overrides.yaml:
nice catch. BTW I tried it with `make osp_full` only.

2021-05-12 20:04 UTC, EmilienM commented on Makefile
>  local-overrides.yaml:
done @mdbooth

2021-05-14 02:02 UTC, EmilienM commented
This one is ready for review, sorry with the git mess.

2021-05-14 07:26 UTC, mandre approved these changes
Great, just when I needed it ;-)

2021-05-14 07:26 UTC, merged